### ISSUE TITLE
sis client scripts work fine with sispy 0.3.12, but does not work with 0.4 release 

### ISSUE THREAD

**Issue by yasir091** [sis-cmdb/sis-python#12]
My sis client scripts work fine with sispy version 0.3.12, but does not work with 0.4 release.  

I get following errrors at the python command line. 

Traceback (most recent call last):
  File "externals/libraries/sis-inventory/sisinv.py", line 227, in <module>
    inv.run()
  File "externals/libraries/sis-inventory/sisinv.py", line 21, in run
    self.add_hosts()
  File "externals/libraries/sis-inventory/sisinv.py", line 171, in add_hosts
    hosts = host_ep.fetch_all(fetch_query)
  File "/usr/lib/python2.6/site-packages/sispy/endpoint.py", line 38, in fetch_all
    response = self.fetch_page(query)
  File "/usr/lib/python2.6/site-packages/sispy/endpoint.py", line 24, in fetch_page
    return self._get(query=query)
  File "/usr/lib/python2.6/site-packages/sispy/endpoint.py", line 121, in _get
    return self.client.request(request)
  File "/usr/lib/python2.6/site-packages/sispy/client.py", line 38, in request
    return self._http_handler.request(request)
  File "/usr/lib/python2.6/site-packages/sispy/http.py", line 187, in request
    prepped = self._session.prepare_request(req)
AttributeError: 'Session' object has no attribute 'prepare_request'

Thanks,
Yasir.

**Comment by antongavrik** [comment]
This is due to an old version of requests library installed, requests 2.0+ is needed to work correctly. The next release of sispy will not attempt to use requests if it's version is below the needed minimum.

**Comment by antongavrik** [comment]
resolved in 1.0.0
